version: '3'

services: 
    practice_db:
        build: ./db
        tty: true
        ports: 
            - "3306:3306"
        container_name: practice_db
        volumes: 
            - ./db/mysql-data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: practice

    practice_golang:
        build: ./go
        tty: true
        ports:
            - "8080:8080"
        container_name: practice_golang
        links:
            - practice_db
            - practice_react
        volumes:
            - ./go:/go/src
            
    practice_react:
        build: ./react
        tty: true
        ports: 
            - "3000:3000"
        container_name: practice_react
        volumes: 
            - ./react:/usr/src