version: '3'

services: 
    sample_golang:
        build: ./go
        tty: true
        ports:
            - "8080:8080"
        container_name: sample_golang
        depends_on:
            - sample_db
        volumes:
            - ./go:/go/src

    sample_db:
        build: ./db
        tty: true
        ports: 
            - "3307:3307"
        container_name: sample_db
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sample

    sample_react:
        build: ./react
        tty: true
        ports: 
            - "3000:3000"
        container_name: sample_react
        volumes: 
            - ./react:/react